---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  notify: restart nginx

- name: Deploy custom index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart nginx

- name: Allow HTTP traffic on port 80
  ansible.builtin.ufw:
    rule: allow
    port: 80
    proto: tcp
